### ISSUE TITLE
Question about modeling

### ISSUE THREAD

**Issue by jcostello** [Altoros/rails-interview-exercise#1]
Given the description:
```
Each Question has an asker (a user), and each Answer has a provider (another user). The only attribute needed for users is a full name.

A Tenant is a consumer of the API you are going to write. Like users, the only attribute needed for tenants is a name. Questions can be private, to be seen only by their Tenant.
```

Since a Tenant that consumes the API and Questions can be private, to be seen only by their Tenant, is OK to assume that Tenant are Users and is the asker in a Questions? The API should return the Tenant asked Questions?

Also, its a requirement to not return private Questions in the API response. But before it says that Questions can be seen only by their Tenant. This is a little bit contradictory. 
Since Tenant refers to a API consumer, where it should return private Questions?

**Comment by tolosa** [comment]
Hi Juan! Nice to meet you. 😃 

You're right, there's no relationship between the Tenant and the questions, the API key is just to get the Tenant identity so you can do the tracking of the number of calls to the API. You can omit that part about restrict questions by Tenant (I will edit the README now). You can just omit private questions from the API responses, without further validation (unless you want to add additional authentication and authorization logic, but I don't think is necessary for this exercise).

Feel free to ask here if you have more questions.

See you in the interview!

**Comment by jcostello** [comment]
Hi Leonardo, nice to meet you too.

Great so, in conclusion:
* Tenant is only to access the API. No relation with any model of the database.
* The API returns only private questions. (Authorization logic is not necessary)

Thank you for the response

See you in the interview. Have a nice weekend
